---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss-deployment
  labels:
    app: jboss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jboss
  template:
    metadata:
      labels:
        app: jboss
    spec:
      # initContainers:
      # - name: add-admin-user
      #  image: quay.io/wildfly/wildfly
      #  command:
      #  - /bin/sh
      #  - -c
      #  - |
      #    /opt/jboss/wildfly/bin/add-user.sh admin Admin12345 --silent
      #  volumeMounts:
      #  - name: wildfly-config
      #    mountPath: /opt/jboss/wildfly/standalone/configuration
      containers:
      - name: jboss
        image: docker.io/islamaboalkhair/wildfly:v1 
        ports:
        - containerPort: 5555  # Custom HTTP port
        - containerPort: 7777  # Custom HTTPS port
        - containerPort: 9990  # condole port 
          #args:
          # - "/opt/jboss/wildfly/bin/standalone.sh"
          # - "-b"  # Bind to all network interfaces for HTTP/HTTPS
          # - "0.0.0.0"
          # - "-bmanagement"  # Bind the management interface to all network interfaces
          #- "0.0.0.0"

          #   command:
          # - "/bin/sh"
          # - " -c"
          # - "|"
          # "/opt/jboss/wildfly/bin/add-user.sh admin Admin12345 --silent"
        env:
          #     - name: WILDFLY_USER
          #  value: "admin"
          # - name: WILDFLY_PASSWORD
          # value: "12345678910"
        - name: JAVA_OPTS
          value: "-Djboss.http.port=5555 -Djboss.https.port=7777 -Djavax.net.ssl.keyStore=/opt/jboss/wildfly/standalone/configuration/application.keystore -Djavax.net.ssl.keyStorePassword=password"
        volumeMounts:
        - name: jboss-keystore
          mountPath: /opt/jboss/wildfly/standalone/configuration/application.keystore
          subPath: application.keystore
      volumes:
        # - name: wildfly-config
        #configMap:
          #  name: wildfly-logging-config
          #  - name: wildfly-config
          # emptyDir: {}
      - name: jboss-keystore
        secret:
          secretName: jboss-keystore-secret  # Secret containing keystore.jks

---
apiVersion: v1
kind: Service
metadata:
  name: jboss-service
  labels:
    app: jboss
spec:
  selector:
    app: jboss
  ports:
    - protocol: TCP
      nodePort: 30555
      port: 5555   # Expose custom HTTP port
      targetPort: 5555
      name: http
    - protocol: TCP
      nodePort: 30777
      port: 7777   # Expose custom HTTPS port
      targetPort: 7777
      name: https
    - protocol: TCP
      nodePort: 30990
      port: 9990   # Expose custom managment port
      targetPort: 9990
      name: managment
  type: NodePort   # Allows external access to the service

---
apiVersion: v1
kind: Secret
metadata:
  name: jboss-keystore-secret
type: Opaque
data:
  application.keystore: MIIKlAIBAzCCCj4GCSqGSIb3DQEHAaCCCi8EggorMIIKJzCCBa4GCSqGSIb3DQEHAaCCBZ8EggWbMIIFlzCCBZMGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFPrgC4WnyqbeeKvKSVGC4XgFmTogAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQShAyB9YFFsjRNhnMFVD5qgSCBNBjzWR8sLi3S8w6+OC/IL606p+GUtpZkjSnC2r0/DwbPabajC8TPPpVwJ8lIE/LxXcHRLTt+5/+n1dSApZwLTJr+2FxCOxCWH9uaNzlHnETNvQxMi0LDyCdBbHpDTBzh8fwDJJ7MFx/MQR62gslnLBt4GFjxW0p4Lm0EAE/HlsIb4NL6azRxiFRF4mbX/oDKxujetuO3C4zgSMtkN4+iPWWwpXpt6ItD3QxclQv9918iri6atGa+YuB9g07h4Sx5sKlvKQNgujlSsnpM98c0bzLhKMf1eyboS+YKP5H+4mxZ/le4wtD26B/5soG4ycKljWRidSYe/Ksxith/pKgaI9uY/ReEdJPHYqB8RBB92L8zhI+kvtl4k8FqJLDagqz65U0XMWAqr3HC1JEPmW0RNDSV6wKfUnf0r/g6RJ0gncbWeM/S3LPOY/tw1Ki/Iu7AqsZhVkaLvAfYUuyH5tCqFbnsWWv4Xod4FJoy7fCx/3+HPUn16foOPJ8kKmvSIn/qOxqV/STOhjVJLRtAAOBHs19UGt72J9iutonMs5/yj/5WSOgLYeRsL2yXH+SL+Y22j3/hjgdn9D7j3caVZH6rO+lvI6c9HtSZoY8+sX8Leu5UqMB1CpuZd8XDebw5VPoxRzsKkvPV7aVZex6JIPydbvDnu7vSa1ZrnQq/2AlvdQC7rjylndW6DOG1KIOv8OpArtrPpCn4SELjnn5JwHJScYiT9IPfq46/MXge5h+EUHZiPUGHN9bfT/v1pFIxhdCWGr5Dq9BK1XiW4mjbpR2EYsYLlSeHuNpl3uTz3vbHa3HI+WZ/Sysdy/aiPchFM5W6BgH2ptwdy/FCOnIL55YXkemlFLY3q5e8gKnWLNDgedkcFCezKKS2s7E5QBkWZajuA8SvQKs8EeKr6gkaJJnibp5aiCKu421GadDO3RbSxQlSHMKVz5H5MuqWmYjetghGd5PHctkMX4FUIyaIvM9U0OzNirrGcWtVWEusVQ2IgWWOILrWkdDFTK8e+BQ6PClj2WeHXHIfdu+BzcYcKzTBTvd6Q3Z9LINlxGiPYIN2wgCtBAuHtlh/jrumdJPLN46kt8zMhj6H9j+WnDVOVUzM1caPZNncL4+0rPqDrIuVNMC/eFfvTAB05vIJjbg87vgvlS8mohYmNbtuSAMHA+5Rh8d1bOfiYjTTmcP3j3aXbxyJhwTkJ+uD+PkMgh3NgqdLY8A8FnBIi6Mwqt8jqNEwytbBA1keChUX77v2wXgzdP07/G9By/45t/mh4bk5QKbcUh/J9h4dmwLaBqKN0kh5eOdV6GEM05WMrcDXABGu8/fwgQY5hwq7Vy9EJues3U4q3pRmUg3EYrYF0hbBhmNPfeCi+NmNR5+LQhNAd8I5n/x/hxWj29KnZCxES1lihIzrUVb0Dj7bmKgkjzgQhXcH3XDNCosCdL9jYaq4C93MTD65IhE4xJMy6hLwaTC1YFcdIVQdJ4rlTRuFwE7z8NZd50/mXGExvEn5kfaLllKHcc7mpKHk0+YDBcApxPchmtuMQQy7Sw4MpZIkGYkBk/UztiU98fgmuWws6BPxF9KU7Qv44wowtjdn8ZuqQlPYyfZnb0qAb2fbK/MRtCyx+/NaO2iEh7pDDN59O40Aq8CuBMoWTFAMBsGCSqGSIb3DQEJFDEOHgwAcwBlAHIAdgBlAHIwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTcyNjc0MDE0Njc5MDCCBHEGCSqGSIb3DQEHBqCCBGIwggReAgEAMIIEVwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBRTy6HuVzo3jzpW6St1iXzajTv87QICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEKalAZbWZq90zt/mAHX3NtWAggPgwaSGOH2n97/QultVLEPB8ttgNpg0FwvyE14brkgANoApPYSJ0b4AYk1+rpU+M/HVwJKF5Tx0jgsZV6WD0glqLTLizRLbHTrLXSPFRS2XdFTvtu48Utz2JX4v1RvQ1UlkLj03CVFUc/Ptz8EXBgEp3jhyaaf870bZdhmNtDKf3PW8WCmt7/yJCEcWyIIG5Mv30gKdA+8MauSv/8X2NiBVV0DBTBppyQKQjmJVxasP5U/usgMnAqEWWpUXYdwVrkw6yML/H+4o65eV9Yv9VTpYcKM9br8k9qIzADaWN7EchZLzTGTXexnW/UQ16UVHeWyjH1XFtSL2Wnbleiq1u/ONX0OQcZsJD7mBEcXF4gY22vsTmS0xLsm9FcH8p9hU8QCvdvmzk3o/4jNrLBihjJrf52JQBXbuqarZ+7XMV2zyuCwSh3+pk28r0Pt2vzxf+6bIlgw0t8eJBoE8bL6C5hZb1ToCp+SoB2XrAyt/tCH4fR33Vs/nf1QyrBWwrTamX87CrfQ6pQsvmza+m80Ym05g54z6QGh2pA66IxnS+wcAdNeTT4/lJ2pm2aEcuCPYugQjFrbyhqPl0VVZlFVnOaKaKBnWSALRvhCHOXzSCGLn5zF5FXwNkX9Yt5k7iiB0nfv06hR6zAkd08he7Cu7ht1XpHIV+Y62hpj/0/7l0Aaw8prLfJ1I8tHyHnSGBqtPxK7rjMbzA5Diuzud2Ocu96tBoJ6/4w7TPDmgaiCr2q8QSwDxPfpGRTcyjXPpPqpFrC5GVNDMJMOQFGr+SGtIprbujG+hiF9e7Iy2ZPFMSNuDuzVdK+NaBhL/CaUI4CvbDKN+ahJw8cCGncZ/dSncPLrVpUDp/ZJTZ6IZn09fRUpJFmAcwy6yPS4JM+qwAB6hyM9tJOaljUJ14HT8NDmtKXAWMCnKHG3d+WZdLGryAM461ZLPYZxnPZxiNIP4aUCuKY/kJlhLXldx2OTarAoEXFxHP5s1N7B81npK6+OzWyNZxi1jIAB4KFmVMlPU9sB/ePMkOc+gNhSNZhZEhVQN++65D3orRIPn70ziuHXdwoIQq2l4QqVCevP9Zpc7HtuhhF10EBD/XpicYNg/iTi1dA0RbzDn9y3RdrY4N0AUsCSfLAWxOmAH6jZd3Eh0HgZ+0JYSudeYQSM1NoDEGHzqYKHVBcr/qhILMQfMv17Lr5FBgPYxsvjQzjuAEizYfVLbwapWE7PY55RpQ8Q3wwK9QZmmLbaulVW1zfOLL/q0b0qrepssUMrAKL2xWdGwDgNjCnUeRDXji/XnpHYIAZfjfcoNs4hp+GBqTgpog91EYF4KQEgwTTAxMA0GCWCGSAFlAwQCAQUABCAqq4nsMIB86ivRvfTJ+SmoEXdnFNaKp2JE9Z33yTW0IQQU7Q+6/sZcwoSuB2B1CZGZJLj/my8CAicQ
